---
apiVersion: v1
kind: Service
metadata:
  name: foglamp-manage-db
  #namespace: foglamp-manage
spec:
  type: ClusterIP
  ports:
  - name: 5432tcp2
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: foglamp-manage-db
