apiVersion: v1
kind: Service
metadata:
  name: foglamp-manage
  labels:
    name: foglamp-manage
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    name: port-1
  - port: 5001
    targetPort: 5001
    name: port-2
  - port: 5002
    targetPort: 5002
    name: port-3
  selector:
    name: foglamp-manage
