apiVersion: v1
kind: Pod
metadata:
        name: fogman-pod
        labels:
                env: prod
spec:
        containers:
                - name: fogman-db
                  image: 54.204.128.201:5000/foglamp-manage-db:test-k8s
                  ports:
                  - containerPort: 5432
                  env:
                  - name: POSTGRES_USER
                    value: fogman
                  - name: POSTGRES_PASSWORD
                    value: fogman
                  - name: PKG_VERSION
                    value: nightly
                  - name: ARCHIVE_REPO_USERNAME
                    value: dianomic
                  - name: ARCHIVE_REPO_PASSWORD
                    value: Foglamp200
                    #args: ["$(PKG_VERSION) $(ARCHIVE_REPO_USERNAME) $(ARCHIVE_REPO_PASSWORD)"]      
                - name: fogman
                  image: 54.204.128.201:5000/foglamp-manage:test-k8s
                  ports:
                  - containerPort: 5000
                  - containerPort: 5001
                  - containerPort: 5002
                  env:
                  - name: FOGMAN_DB_HOST
                    value: 127.0.0.1
                  - name: FOGMAN_ENV
                    value: container
                    #args: ["$(PKG_VERSION) $(ARCHIVE_REPO_USERNAME) $(ARCHIVE_REPO_PASSWORD)"]
