apiVersion: v1
kind: Service
metadata:
  name: fogman-pod
  labels:
    run: fogman-pod
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    name: port-1
  - port: 5001
    targetPort: 5001
    name: port-2
  - port: 5002
    targetPort: 5002
    name: port-3
  selector:
    run: fogman-pod
