# Create Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foglamp-manage-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
