apiVersion: v1
kind: Pod
metadata:
        name: fogman-pod
        labels:
                env: prod
spec:
        containers:
                - name: fogman-db
                  image: 54.204.128.201:5000/foglamp-manage-db:test-k8s
                  ports:
                  - containerPort: 5432
                  env:
                  - name: POSTGRES_USER
                    value: fogman
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: fogman-auth
                        key: POSTGRES_PASSWORD
                  - name: PKG_VERSION
                    value: nightly
                  - name: ARCHIVE_REPO_USERNAME
                    value: dianomic
                  - name: ARCHIVE_REPO_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: fogman-auth
                        key: ARCHIVE_REPO_PASSWORD
                  volumeMounts:
                  - mountPath: /var/lib/postgresql/data
                    name: foglamp-manage-db-data
                    subPath: postgres
                - name: fogman
                  image: 54.204.128.201:5000/foglamp-manage:test-k8s
                  ports:
                  - containerPort: 5000
                  - containerPort: 5001
                  - containerPort: 5002
                  env:
                  - name: FOGMAN_DB_HOST
                    value: 127.0.0.1
                  - name: FOGMAN_ENV
                    value: container


        volumes:
        - name: foglamp-manage-db-data
          persistentVolumeClaim:
            claimName: foglamp-manage-db-data
        - name: foglamp-manage-data
          persistentVolumeClaim:
            claimName: foglamp-manage-data
