#https://cloud.google.com/artifact-registry/docs/access-control#pullsecrets
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foglamp-deployment
    name: foglamp-deployment
  name: foglamp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foglamp-deployment
      name: foglamp-deployment
  template:
    metadata:
      labels:
        name: foglamp-deployment
        app: foglamp-deployment
    spec:
      containers:
      - name: foglamp-deployment
        image: us-central1-docker.pkg.dev/foglamp/demo-repo/foglamp:v1
        imagePullPolicy: Always
        ports:
        - name: 6683tcp2
          containerPort: 6683
          protocol: TCP
        - name: api
          containerPort: 8081
          protocol: TCP
        - name: https
          containerPort: 1995
          protocol: TCP
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: FOGLAMP_ROOT
          value: /usr/local/foglamp
        volumeMounts:
        - mountPath: /usr/local/foglamp/data
          name: foglamp-data
      volumes:
      - name: foglamp-data
        persistentVolumeClaim:
          claimName: foglamp-data
