---
apiVersion: v1
kind: Service
metadata:
  name: foglamp
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: https
    port: 1995
    targetPort: 1995
    protocol: TCP
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: foglamp-deployment
    name: foglamp-deployment
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 8081
    targetPort: 8081
  - name: https
    port: 1995
    targetPort: 1995
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: foglamp-deployment
    name: foglamp-deployment
