apiVersion: v1
kind: Pod
metadata:
        name: foglamp-pod
        labels:
                env: prod
spec:
        containers:
                - name: foglamp
                  image: 54.204.128.201:5000/foglamp:nightly-ubuntu1804
                  ports:
                  - containerPort: 80
